apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-discovery
  namespace: kube-system
rules:
  # Allow Discovery to see all namespsaces, services, pods, and nodes.
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get","watch","list"]
  # Allow Discovery to see the kube-controller-manager.
  - apiGroups: [""]
    resources: ["endpoints"]
    resourceNames: ["kube-controller-manager"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-discovery
subjects:
  - kind: ServiceAccount
    name: discovery
    namespace: kube-system
