apiVersion: v1
kind: Service
metadata:
  name: sn-acc-mid-INSTANCE_NAME
  namespace: servicenow
  labels:
    run: <<k8s_mid_deployment_name>>
spec:
  type: LoadBalancer
  ports:
  - port: 8800
    targetPort : 8800
    protocol: TCP
  selector:
    app: <<k8s_mid_deployment_name>>
